--- 
title: "Computação em R: Análise experimental"
author: "Eric Bastos Gorgens, Marcio Leles Romarco de Oliveira"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introdução

Delineamento experimental se trata do desenho do experimento. Ou seja, ele define a organização das unidades experimentais em função da pergunta científica que se deseja responder. Com base no delineamento escolhido, regras precisam ser seguidas, especialmente relacionados à maneira que os tratamentos são distribuídos nas unidades experimentais. Este livro apresenta o processamento dos principais delineamentos experimentais por meio da linguagem de programação R. Inicialmente, o livro apresenta o cálculo de uma análise de variância e descreve quais são os principais tipos. Em seguida, por meio de exemplos práticos, são apresentados os principais gráficos para realizar a exploração dos dados e os principais delineamentos amostrais. Por fim, discute-se o que deve ser feito quando os dados não atendem às pressuposições da ANOVA. Propõe-se uma abordagem por meio dos testes não paramétricos. Tudo é apresentado de forma muito prática, utilizando a linguagem de programação R. Com os exemplos apresentados, o leitor é convidado a rodar cada passo junto com o livro. Os dados e os códigos estão livremente distribuídos.

## O R

O R é um software e uma linguagem. Através de seus códigos e *scripts* é possível entrar num mundo aberto à experimentação e à troca de experiência. Um mundo em que não existe apenas uma forma de se chegar à resposta correta, mas sim uma gama de alternativas! 

Por se tratar de um projeto de código aberto, é possível usar o R sem nenhum custo adicional, sem a necessidade de pagar por inscrições, assinaturas ou licenças. Centenas de usuários ao redor do mundo compartilham suas contribuições e beneficiam a toda a comunidade.

No R, a análise é implementada por meio de um *script*. Um *script* documenta o passo a passo da análise, do acesso aos dados até os resultados, podendo ser executado a qualquer momento, em qualquer lugar, por qualquer pessoa. Nada de sair clicando em botões na tela. 

Isto pode assustar e parecer difícil, mas na verdade, a linguagem R é uma linguagem simples de aprender e muito natural para análise de dados. Aprender uma linguagem tem vários benefícios. Por se tratar de uma linguagem interativa, o R promove uma oportunidade de experimentar e explorar os dados de forma profunda e detalhada. 

A visualização dos dados através de gráficos é uma parte essencial de qualquer análise dos dados. Por isto, o R oferece excelentes ferramentas para criação de gráficos, de barras até multi-painéis.

O R apresenta um conjunto de ferramentas prontamente disponíveis, desde o acesso a vários tipos de dados, até recursos para manipulação de dados, passando pelos modelos estatísticos tradicionais e modernos. Todos os recursos estão disponíveis numa plataforma orientada a objeto que torna fácil a programação e construção de relatórios.

Os principais acadêmicos e pesquisadores do mundo utilizam o R para desenvolver as suas análises. Ao compartilhar *scripts*, pacotes e funções, é possível encontrar o que há de melhor na área de modelagem, estatística, econômica, genética e muitos outros campos. Atualmente são mais de 2000 pacotes que incrementam o seu R disponíveis para download.

O R é multiplataforma, rodando em Linux, Mac ou Windows. Ainda é possível configurar para rodar diretamente da nuvem. Com o R, o usuário não está limitado a uma sequência pré-definida de rotinas. Você pode usar todo o portfólio de códigos e soluções disponíveis na comunidade ou mesmo criar suas próprias funções. É possível inclusive combinar o R com outros recursos como uma base de dados MySQL, ou um Apache web-server, ou ainda com o Google Maps API. 

Você está preparado? Qual a sua ideia?